### ISSUE TITLE
Raise exception when creditcard not found

### ISSUE THREAD

**Issue by lucasgomide** [hugolantaume/credit_card_bins#1]
When  run  `'595959.credit_card_bin_brand'`, an exception is raised.
You can return a only `nil`.

**Comment by niltonheck** [comment]
Hi Lucas,

Actually i think that returning a Exception is the best way around. Having methods to rescue from exception is a good practice and lead to better design decisions.

However, i also believe that the exception should be more clear. I spent a couple hours to identify that a customer's credit card were out of the lib's range.

Let me know what you think and we could add this "fix" as a pull request.

**Comment by lucasgomide** [comment]
I agree with you !

Look:

```
'595959'.credit_card_bin_brand
NoMethodError: undefined method `[]' for nil:NilClass
    from /Users/lucasgomide/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/credit_card_bins-0.0.1/lib/credit_card_bins/bin.rb:33:in `brand'
    from /Users/lucasgomide/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/credit_card_bins-0.0.1/lib/credit_card_bins/string.rb:7:in `credit_card_bin_brand'
    from (irb):73
    from /Users/lucasgomide/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/console.rb:110:in `start'
    from /Users/lucasgomide/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/console.rb:9:in `start'
    from /Users/lucasgomide/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:68:in `console'
    from /Users/lucasgomide/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
    from /Users/lucasgomide/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/commands.rb:17:in `<top (required)>'
    from bin/rails:4:in `require'
    from bin/rails:4:in `<main>'
```

Its broken here https://github.com/hugolantaume/credit_card_bins/blob/master/lib/credit_card_bins/bin.rb#L33

The purpose that issue is: when  creditcard has no brand, should not return a error `NoMethodError: undefined method [] for nil:NilClass`. Should raise a exception `NotFound` or a nil object.

What's you think?

**Comment by niltonheck** [comment]
You're right. We should return a `NotFound` exception. I'll fix this soon.

**Comment by lucasgomide** [comment]
Nice !! 

(:

tks
